# Generated by Django 3.1.2 on 2021-09-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='firstcollege',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others'), ('Not disclosed', 'Not disclosed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='race',
            field=models.CharField(choices=[('White', 'White'), ('Asian', 'Asian'), ('Black', 'Black'), ('American Indian', 'American Indian'), ('Hispanic', 'Hispanic'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
