# Generated by Django 3.1.2 on 2021-09-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210925_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Gender', 'Gender'), ('Race', 'Race'), ('firstcollege', 'firstcollege')], max_length=100, null=True)),
            ],
        ),
    ]
