# Generated by Django 3.1.2 on 2021-09-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Female', 'Female'), ('Black', 'Black'), ('American Indian', 'American Indian'), ('Hispanic', 'Hispanic'), ('firstcollege', 'firstcollege')], max_length=100, null=True)),
                ('points', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
